Create admin and user admin
locokit/locokit pull request #216
Opened 2023-03-07 15:14 UTC by Alketta

Close #208

2023-03-17 17:20 UTC, mdartic requested changes
Thanks for this work !

Stories with Histoire are really nice to read.

Some questions : 
* how to handle prop in `ButtonWithStatus` or `MessageUser`, and more generraly, when the value of the prop is a translation key. Do we need another prop specifying this is a translation key ? Do we need another name for the prop hosting the label ?
* I don't well understand the admin about page, I think I need to test it on my PC

This review is only a review of code.

No tests have been made on the browser.

2023-03-17 17:20 UTC, mdartic commented on packages/nuxt-locokit/src/pages/admin/index.vue
> +        :to="{ name: ROUTES_NAMES.HOME }"
this is a work in progress, and will be updated when the group page will be implemented ?

2023-03-17 17:20 UTC, mdartic commented on packages/nuxt-locokit/src/pages/auth/ResetPassword.vue
> +  }
Do we need to manage the usecase when there is no `route.query.token` ?

2023-03-17 17:20 UTC, mdartic commented on packages/nuxt-locokit/src/pages/auth/VerifySignup.vue
> +  }
Same when there is no token ?

2023-03-17 17:20 UTC, mdartic commented on packages/nuxt-locokit/src/paths.ts
> +      RECORD: 'RECORDlUser',
```suggestion
      RECORD: 'RecordUser',
```

2023-03-20 09:54 UTC, Alketta commented on packages/designsystem/src/components/auth/LostPasswordForm/LostPasswordForm.vue
> +        label="components.lostPasswordForm.submit"
It depends. 
We need to discussed about this. 
In your case (in LocoKit), a translation key is always used (so no need for computed)

2023-03-20 09:56 UTC, Alketta commented on packages/designsystem/src/components/profile/UpdateGeneralForm/UpdateGeneralForm.vue
> +const username = ref(props.user.username)
I think we should respect the spelling.

2023-03-20 09:57 UTC, Alketta commented on packages/designsystem/src/index.ts
> +  MessageForUser,
Nope, I am used to

2023-03-20 09:59 UTC, Alketta commented on packages/designsystem/src/stories/FilterButton.story.vue
> +      <div id="test">
It is for the [Teleport](https://vuejs.org/guide/built-ins/teleport.html). This is used in Prime with `appendTo`.

2023-03-20 10:13 UTC, Alketta commented on packages/designsystem/src/stories/MessageForUser.story.vue
> +    </Variant>
It shows 4 different visuals. 
I am not using `Variant` for each one because it is not necessary.

2023-03-23 14:49 UTC, mdartic commented on packages/designsystem/src/components/auth/SignInForm/SignInForm.vue
> +          custom-msg-error-form="error.notAuthenticated.description"
Maybe rename the prop here too.

2023-03-23 14:52 UTC, mdartic commented on packages/designsystem/src/components/profile/UpdateGeneralForm/UpdateGeneralForm.vue
> +const username = ref(props.user.username)
All right, so `firstname` becomes `firstName` and `lastname` becomes `lastName`, but `username` stays `username`.
That's it ?

2023-03-23 14:55 UTC, mdartic commented on packages/nuxt-locokit/src/interfaces/toMigrate.ts
> +// Todo: to retrieve from definition
Ok, could you create an issue for this ?

2023-03-23 14:58 UTC, mdartic commented on packages/nuxt-locokit/src/pages/auth/VerifySignup.vue
> +  }
up

2023-03-29 09:35 UTC, mdartic commented on packages/designsystem/src/stories/FilterButton.story.vue
> +      <div id="test">
Now this is more clear, that's fine.

2023-04-04 07:48 UTC, merged