[ds] Add primevue unstyled + tailwind presets (aura / lara)
locokit/locokit pull request #262
Opened 2024-05-31 13:01 UTC by mdartic

* remove screenshots for histoire
* add packages versioning for i18n & designsystem (for publishing purpose & reuse in capel project)
* add w-full classes on input / password components, and remove p-fluid in forms

2024-06-25 17:26 UTC, mdartic commented
CI is not working as it is not the aim of this PR.
The PR #264  is here to fix the CI by passing to pnpm.

2024-07-01 09:07 UTC, Alketta requested changes
I didn't check on primevue file (Aura),, I guess you remove the override in these files.
In fact, I wonder if I should keep them.

2024-07-01 09:42 UTC, mdartic commented on packages/designsystem/src/index.ts
> +    // pt: Aura,
Indeed, I remove the local preset files.

2024-07-01 09:46 UTC, mdartic commented on packages/designsystem/package.json
> +    "@vitejs/plugin-vue": "^5.0.5",
Don't know, seems there are some deps twice in dependencies section.
I remove them.

2024-07-01 09:47 UTC, mdartic commented on packages/designsystem/src/layouts/background.story.vue
> +import PCard from 'primevue/card'
Right, done.

2024-07-01 09:48 UTC, mdartic commented on packages/designsystem/src/plugins/primevue.ts
>  export function definePluginPrime(app: App): void {
The `definePluginPrime` is only for prime whereas `setupLckDesignSystem` is larger than that, and exposed in the "root" exports of the package.
It allows the user of the `@locokit/designsystem` package to configure with only one function the design system, with prime, i18n and vee-validate.

2024-07-01 13:38 UTC, Alketta approved these changes

2024-07-01 13:43 UTC, merged