feat: Enhance vue-components package
locokit/locokit pull request #321
Opened 2024-12-16 14:09 UTC by mdartic

* add AutoComplete, SingleSelect, Date, DateTime, ToggleSwitch fields
* update field component typing (@locokit/definitions)
* fix layout background typing for slots

related to #316

2024-12-18 16:13 UTC, Lonnytunes requested changes

2024-12-18 16:13 UTC, Lonnytunes commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +              :class="f.class"
```suggestion
              :class="f.class"
              :labelId="f.id"
```

If I understand the documentation, it's `labelId` now to attribute an `id` to the `<select>`, but you should check cause I'm not really sure.

2024-12-18 16:13 UTC, Lonnytunes commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +              :class="f.class"
```suggestion
              :class="f.class"
              :inputId="f.id"
```

2024-12-18 16:13 UTC, Lonnytunes commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +    autocompleteSuggestions?: unknown[]
I don't understand this property. Isn't a property of autocomplete fields?

2024-12-19 13:17 UTC, Lonnytunes commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +    autocompleteSuggestions?: unknown[]
After our discussion this morning, I understand now :wink:

2025-01-06 13:23 UTC, mdartic commented on packages/definitions/src/fieldType.ts
> +   * Source for the data component
Done

2025-01-06 13:23 UTC, mdartic commented on packages/vue-components/README.md
> +> Some evolutions could break retrocompatibility through versions until we reach the 1.x .
Done

2025-01-06 13:24 UTC, mdartic commented on packages/vue-components/README.md
> +// import separately
Done

2025-01-06 13:24 UTC, mdartic commented on packages/vue-components/README.md
> +Autocomplete for properties and event is provided in IDE like VS Code :
Done

2025-01-06 13:25 UTC, mdartic commented on packages/vue-components/README.md
> +used in vue-components.
Done

2025-01-06 14:00 UTC, mdartic commented on packages/definitions/src/fieldType.ts
> +  helpText?: string[]
As @SimonMellerin suggest, `description` could be more usual.

Check framforms :

![image](https://github.com/user-attachments/assets/8506001e-9475-4f01-8e31-4ddb3c7579c8)

or VueForm builder

![image](https://github.com/user-attachments/assets/e832f1f4-472e-4215-95ae-a23b41d445aa)

Nonetheless, I think a `string[]` typing is better than a single string, as it allows us to display a description on a multi line. We can discuss this point tomorrow DM.

2025-01-06 14:12 UTC, mdartic commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +            />
Done

2025-01-06 14:13 UTC, mdartic commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +              :class="f.class"
Done

2025-01-06 14:13 UTC, mdartic commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +              :class="f.class"
Done

2025-01-06 14:15 UTC, mdartic commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +              :class="f.class"
You seem right https://primevue.org/select/#api.select.props.labelId, `inputId` is deprecated.

Done

2025-01-06 14:16 UTC, mdartic commented on packages/vue-components/components/commons/generic-form/generic-form.stories.ts
> +  }),
Not really, I'm used to the `setup` function, but I update the code to be more consistent.

2025-01-06 14:26 UTC, SimonMellerin commented on packages/definitions/src/fieldType.ts
> +  helpText?: string[]
Why not just deal with multi-line inside the string ?

(Ideally, it could be markdown compatible :innocent: )

my two cents ^^

2025-01-07 08:57 UTC, mdartic commented on packages/definitions/src/fieldType.ts
> +  helpText?: string[]
Conclusion : `description: string | string[]`

2025-01-07 11:31 UTC, Lonnytunes commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +              :class="f.class"
Did you check the resulting code? Because I'm currently working to migrate the `FilterButton` component, and I finally used `:id` instead of `:labelId` for my `PrimeSelect` components.

2025-01-07 11:37 UTC, mdartic commented on packages/vue-components/components/commons/generic-form/generic-form.vue
> +              :class="f.class"
Well, on my storybook I have this for a `SINGLE_SELECT` with an `id` which value is `select`: 
![image](https://github.com/user-attachments/assets/82f651f1-a0a5-46db-a195-2bffb04983d7)

For me it seems OK ?

2025-01-07 12:20 UTC, Lonnytunes approved these changes

2025-01-07 12:52 UTC, merged